name: Test Reusable - Permissions Test

on:
  workflow_call:
    inputs:
      project-display-name:
        type: string
        default: ''

permissions:
  contents: read
  checks: read

jobs:
  hello:
    name: Hello World
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "workflow-level permissions test"
