name: Test Reusable - Job-Level Permissions

on:
  workflow_call:
    inputs:
      project-display-name:
        type: string
        default: ''

jobs:
  hello:
    name: Hello World
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: read
    steps:
      - name: Say hello
        run: echo "job-level permissions test"
